name: Build and Deploy Render

on:
  push:
    branches:
      - "main"

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request to RENDER_DEPLOY_HOOK
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null ${{ secrets.RENDER_DEPLOY_HOOK }})
          if [ "$response" -eq 200 ]; then
            echo "Request succeeded with status code $response"
          else
            echo "Request failed with status code $response"
            exit 1
          fi
